#ifndef LORA_LORA_TIMMINGS_H
#define LORA_LORA_TIMMINGS_H

#define TIME_SLOT_MS 500
#define LISTEN_AHEAD_MS 50
#define WDT_DELTA 50
#define SERVER_SLOT 0
#define BROADCAST_SLOT 1
#define NR_OF_SLOTS 10
#define NR_OF_DEVICES (NR_OF_SLOTS - 2)

#endif
